dubbo:
  scan:
    base-packages: com.marvel.thanos.order.rpc
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
#   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#   address: zookeeper://192.168.0.133:2181
  application:
    logger: slf4j
    qos-port: 22223

feign:
  hystrix:
    enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata
logging:
  config: classpath:logback.xml