server:
  port: 8082
spring:
  cloud:
    gateway:
      default-filters:
      routes:
        - id: product_route
          uri: http://localhost:8080/products
          predicates:
            - Path=/products,/products/*
        - id: order_route
          uri: http://localhost:8081/orders
          predicates:
            - Path=/orders,/orders/*