dubbo:
  scan:
    base-packages: com.marvel.thanos.product.rpc
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
#   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata
logging:
  config: classpath:logback.xml